name: Build

on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Create Windows Release
    runs-on: windows-latest
    steps:
      - run: echo "The job was automatically triggered by a actions event named; ${{ github.event_name }}."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your repository is ${{ github.repository }}and your branch is ${{ github.ref }} ."
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          ref: WorkInProgress
      - run: echo "[STATUS] is; ${{ job.status }}."
      - run: pip install pyinstaller
      - run: pip install pillow
      - run: echo "[STATUS] is; ${{ job.status }}."
      - run: pyinstaller --onefile --windowed --name drawio-cable-labler --icon ./icon/icon.iconset/icon.icns window.py
      - run: dir
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/drawio-cable-labeler.exe
