name: Build
on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
jobs:
  build:
    name: Create Windows Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Build with py2exe
        run:
          pip install -r requirements.txt
          pip install py2exe
          py setup.py install
          py setup.py py2exe