name: Build

on:
  push:
#     tags:
#       - '*'
jobs:
  release:
    strategy:
      matrix:
        os: [  windows-latest ]
        
    name: Create ${{ matrix.os }} Release
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "The job was automatically triggered by a actions event named; ${{ github.event_name }}."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your repository is ${{ github.repository }} and your branch is ${{ github.ref }} ."
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
      - run: echo "[STATUS] is ${{ job.status }}."
      - name: Generate Execulaable 
        run: pyinstaller --onefile --windowed --name drawio-cable-labler --icon ./icon/icon.iconset/icon.icns window.py
      
      - name: test ${{ matrix.os }}
        if:  runner.os == "windows"
        run: |
          echo "${{ matrix.os }}"
          ls dist
        
#       - name: Release Windows Executable
#         if: matrix.os == "windows-latest" && startsWith(github.ref, 'refs/tags/')
#         uses: softprops/action-gh-release@v1
#         with:
#           name: Windows EXE
#           files: dist/drawio-cable-labler.exe
#           body_path: changelog.md
          
#       - name: Release MacOS Executable
#         if: matrix.os == "macos-latest" && startsWith(github.ref, 'refs/tags/')
#         uses: softprops/action-gh-release@v1
#         with:
#           name: MacOS App
#           files: dist/drawio-cable-labler.app
#           body_path: changelog.md
      
#       - name: Release Linux Executable
#         if: matrix.os == "macos-latest" && startsWith(github.ref, 'refs/tags/')
#         uses: softprops/action-gh-release@v1
#         with:
#           name: Linux Executable
#           files: dist/drawio-cable-labler
#           body_path: changelog.md
      
      
