name: Build

on:
  push:
    tags:
      - '*'
jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
        
    name: Create ${{ matrix.os }} Release
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "The job was automatically triggered by a actions event named; ${{ github.event_name }}."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your repository is ${{ github.repository }}and your branch is ${{ github.ref }} ."
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
      - run: echo "[STATUS] is; ${{ job.status }}."
      - name: Generate Execulaable 
        run: pyinstaller --onefile --windowed --name drawio-cable-labler --icon ./icon/icon.iconset/icon.icns window.py
      - name: Release Windows
        if: ${{ matrix.os }} == "windows-latest"
        uses: softprops/action-gh-release@v1
        with:
          files: dist/drawio-cable-labeler.exe
          body_path: changelog.md
          
      - name: Release MacOS
        if: ${{ matrix.os }} == "macos-latest"
        uses: softprops/action-gh-release@v1
        with:
          files: dist/drawio-cable-labeler.app
          body_path: changelog.md
      
      - name: Release Linux
        if: ${{ matrix.os }} == "macos-latest"
        uses: softprops/action-gh-release@v1
        with:
          files: dist/drawio-cable-labeler
          body_path: changelog.md
      
      
