name: Build

on:
  push:
#     tags:
#       - '*'
jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
        
    name: Create ${{ matrix.os }} Release
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "The job was automatically triggered by a actions event named; ${{ github.event_name }}."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your repository is ${{ github.repository }} and your branch is ${{ github.ref }} ."
      
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
          
      - name: Generate Execulaable 
        run: pyinstaller --onefile --windowed --name drawio-cable-labler --icon ./icon/icon.iconset/icon.icns window.py
      
      - run: ls dist/
      
      - name: Release Windows Executable
        if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: changelog.md
          
      - name: Release macOS and Linux Executable
        if: runner.os == 'macOS' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/drawio-cable-labler.app
          body_path: changelog.md
      

      
