name: Build

on:
  push:
    tags:
      - '*'
jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]
        
    name: Create ${{ matrix.os }} Release
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "The job was automatically triggered by a actions event named; ${{ github.event_name }}."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your repository is ${{ github.repository }} and your branch is ${{ github.ref }} ."
      
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Extra Dependencies - Linix 
        if: runner.os == 'Linux'
        run: pip install attrdict
        
      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
            
      - name: Generate Execulaable 
        run: pyinstaller --onefile --windowed --name drawio-cable-labler --icon ./icon/icon.iconset/icon.icns window.py
      
      - run: |
          ls dist/
          pwd
      
      - name: Install Extra Dependencies - Linix 
        if: runner.os == 'macOS'
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist/drawio-cable-labler.macOS-app.zip dist/drawio-cable-labler.app
      
      - name: Release Windows Executable
        if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: changelog.md
          
      - name: Release macOS app
        if: runner.os == 'macOS' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/drawio-cable-labler.macOS-app.zip
          body_path: changelog.md
      
      - name: Release Linux Executable
        if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: changelog.md
      

      
