name: Build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        
    name: Create ${{ matrix.os }} Release
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "The job was automatically triggered by a actions event named; ${{ github.event_name }}."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your repository is ${{ github.repository }} and your branch is ${{ github.ref }} ."
      
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev
          sudo apt install libgtk-4-dev
          sudo apt install python3-wxgtk4.0
          wget https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
          python -m pip install wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
          python -m pip install -r ./requirements/requirements.txt
          python -m pip install -r ./requirements/post-requirements.txt
          
      - name: Install Dependencies
        if: runner.os == 'macOS'
        run: |
          python -m pip install -r ./requirements/macreq.txt
          python -m pip install -r ./requirements/requirements.txt
          python -m pip install -r ./requirements/post-requirements.txt

      - name: Install Dependencies
        if: runner.os == 'Windows'
        run: |
          python -m pip install -r ./requirements/winreq.txt
          python -m pip install -r ./requirements/requirements.txt
          python -m pip install -r ./requirements/post-requirements.txt

      - name: Generate Executable 
        run: pyinstaller drawio-cable-labler.spec

      - name: create dmg File - ${{ runner.os }}
        if: runner.os == 'macOS'
        run: |
          python -m pip install dmgbuild
          dmgbuild -s ./settings/dmg_settings.py -D app=dist/drawio-cable-labler.app "drawio-cable-labler" drawio-cable-labler.dmg
      
      - name: Release Windows Executable
        if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: changelog.md
          
      - name: Release macOS app
        if: runner.os == 'macOS' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: drawio-cable-labler.dmg
          body_path: changelog.md
      
      - name: Release Linux Executable
        if: runner.os == 'Linux' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: changelog.md
      

      
