name: Test

on:
  push:

jobs:
  release:  
        
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a actions event named; ${{ github.event_name }}."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your repository is ${{ github.repository }} and your branch is ${{ github.ref }} ."
      
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.13'
        
      - name: Install Dependencies
        run: |
          sudo apt-get install libgtk-3-dev
          sudo apt install python3-wxgtk4.0
          pip install pyinstaller
          pip install attrdict
          pip install lxml
          pip install numpy
          pip install Pillow
          pip install six
          pip install wxPython
          

      - name: Generate Executable 
        run: pyinstaller --onefile --windowed --name drawio-cable-labler --icon icon/icon.iconset/icon.icns window.py

    